// AUTO-GENERATED by scripts/generate-api-routes.mjs — do not edit by hand.
// Run `npm run gen:api` to regenerate from openapi/v1.json.

const ENTRIES: { method: string; source: string }[] = [
  { method: "DELETE", source: "^/api/parties/[^/]+/characters/[^/]+$" },
  { method: "GET", source: "^/api/parties/[^/]+/characters/[^/]+$" },
  { method: "PUT", source: "^/api/parties/[^/]+/characters/[^/]+$" },
  { method: "GET", source: "^/api/parties/[^/]+/characters$" },
  { method: "POST", source: "^/api/parties/[^/]+/characters$" },
  { method: "DELETE", source: "^/api/parties/[^/]+/items/[^/]+$" },
  { method: "GET", source: "^/api/parties/[^/]+/items/[^/]+$" },
  { method: "PUT", source: "^/api/parties/[^/]+/items/[^/]+$" },
  { method: "GET", source: "^/api/parties/[^/]+/items$" },
  { method: "POST", source: "^/api/parties/[^/]+/items$" },
  { method: "GET", source: "^/api/parties/[^/]+/stash$" },
  { method: "GET", source: "^/api/parties/[^/]+$" },
  { method: "POST", source: "^/api/parties/join$" },
  { method: "GET", source: "^/api/parties$" },
  { method: "POST", source: "^/api/parties$" },
  { method: "GET", source: "^/health$" },
];

const API_ROUTES = ENTRIES.map((entry) => ({
  method: entry.method,
  pattern: new RegExp(entry.source),
}));

/** Whether the given method + path matches a known API route. */
export function isAllowedRoute(method: string, path: string): boolean {
  const upper = method.toUpperCase();
  return API_ROUTES.some((route) => route.method === upper && route.pattern.test(path));
}
